# forward + backward
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress smart --num_bits_main 6 --num_bits_outlier 8 --measure_compression_ratio --name "smart-stochastic-[forward,backward,weight,grad,momentum]-[6-8]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress fp8 --measure_compression_ratio --name "fp8-[forward,backward,weight,grad,momentum]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress s2fp8 --measure_compression_ratio --name "s2fp8-[forward,backward,weight,grad,momentum]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress fp16 --measure_compression_ratio --name "fp16-[forward,backward,weight,grad,momentum]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress bf16 --measure_compression_ratio --name "bf16-[forward,backward,weight,grad,momentum]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress fp32 --measure_compression_ratio --name "fp32-[forward,backward,weight,grad,momentum]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress smart --num_bits_main 5 --num_bits_outlier 7 --measure_compression_ratio --name "smart-stochastic-[forward,backward,weight,grad,momentum]-[5-7]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress smart --num_bits_main 4 --num_bits_outlier 6 --measure_compression_ratio --name "smart-stochastic-[forward,backward,weight,grad,momentum]-[4-6]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress smart --num_bits_main 3 --num_bits_outlier 5 --measure_compression_ratio --name "smart-stochastic-[forward,backward,weight,grad,momentum]-[3-5]" @args

python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress smart --num_bits_main 6 --num_bits_outlier 8 --measure_compression_ratio --no_compress_momentum_vectors --no_compress_backward --name "smart-stochastic-[forward,weight,grad]-[6-8]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress s2fp8 --measure_compression_ratio --no_compress_momentum_vectors --no_compress_backward --name "s2fp8-[forward,weight,grad]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress smart --num_bits_main 5 --num_bits_outlier 7 --measure_compression_ratio --no_compress_momentum_vectors --no_compress_backward --name "smart-stochastic-[forward,weight,grad]-[5-7]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress smart --num_bits_main 4 --num_bits_outlier 6 --measure_compression_ratio --no_compress_momentum_vectors --no_compress_backward --name "smart-stochastic-[forward,weight,grad]-[4-6]" @args
python ./train.py --accelerator ddp --gpus -1 --model bert --dataset glue --batch_size 10 --val_batch_size 2 --max_epochs 100 --compress smart --num_bits_main 3 --num_bits_outlier 5 --measure_compression_ratio --no_compress_momentum_vectors --no_compress_backward --name "smart-stochastic-[forward,weight,grad]-[3-5]" @args
