# forward + backward
python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress smart --num_bits_main 6 --num_bits_outlier 8 --tags "6,8" --measure_compression_ratio @args
python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress fp8 @args
python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress s2fp8 --measure_compression_ratio @args
python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress fp16 @args
python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress bf16 @args
python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress fp32 @args
python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress smart --num_bits_main 5 --num_bits_outlier 7 --tags "5,7" --measure_compression_ratio @args
python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress smart --num_bits_main 4 --num_bits_outlier 6 --tags "4,6" --measure_compression_ratio @args

python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress smart --num_bits_main 6 --num_bits_outlier 8 --tags "6,8" --measure_compression_ratio --no_compress_momentum_vectors --no_compress_backward @args
python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress s2fp8 --measure_compression_ratio --no_compress_momentum_vectors --no_compress_backward @args
python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress smart --num_bits_main 4 --num_bits_outlier 6 --tags "4,6" --measure_compression_ratio --no_compress_momentum_vectors --no_compress_backward @args
python ./train.py --git --accelerator ddp --gpus -1 --model resnet --dataset cifar10 --batch_size 128 --val_batch_size 64 --max_epochs 250 --scheduler_type multi_step --scheduler_gamma 0.1 --scheduler_milestones 100 150 200 --compress smart --num_bits_main 3 --num_bits_outlier 5 --tags "3,5" --measure_compression_ratio --no_compress_momentum_vectors --no_compress_backward @args
